development: &default
  adapter: mysql
  database: instalover_development
  username: root
  password:
  host: localhost
  encoding: utf8

test: &test
  <<: *default
  database: instalover_test


cucumber:
  <<: *test

production:
  adapter: mysql
  database: instalover_production
  username: root
  password: LastNightsPenis
  host: localhost
  encoding: utf8
